# lib/personal-cmd.sh — personal command wrapper at ~/.local/bin/<name>
#
# After install the operator runs `<name> doctor`, `<name> update`,
# `<name> status`, etc. — short, ergonomic per-instance commands
# instead of long `bash uninstall.sh --name <name>` invocations
# (docs/architecture.md §3d).
#
# The wrapper dispatches to:
#   • `bash <(curl …doctor.sh|update.sh|uninstall.sh) --name <name>` —
#     fetches the latest entrypoint from origin so the operator always
#     runs the current one (mirrors how update.sh already works).
#   • `systemctl --user … claudify-<name>` for status/logs/start/stop/
#     restart (local-only, no network).
#
# Engine-agnostic: nothing here references `claude` or any engine
# adapter — the wrapper only deals with systemctl + Claudify entrypoints.
#
# Exposes:
#   personal_cmd_install <name>     — generate wrapper + ensure PATH
#   personal_cmd_uninstall <name>   — remove wrapper file (idempotent)
#   personal_cmd_ensure_path        — add ~/.local/bin to PATH in rc files
#   personal_cmd_clean_path         — remove the PATH line on full uninstall

CLAUDIFY_PATH_MARKER='# Claudify PATH —'
CLAUDIFY_RAW_BASE='https://raw.githubusercontent.com/didi6135/Claudify/main'

# personal_cmd_install <name>
#   Write the wrapper to ~/.local/bin/<name>, chmod 755, ensure PATH.
#   Honours DRY_RUN. Idempotent — overwrites an existing wrapper so
#   updates regenerate it cleanly.
personal_cmd_install() {
  local name="${1:?personal_cmd_install: name required}"
  local target_dir="$HOME/.local/bin"
  local target="$target_dir/$name"

  if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
    echo "  [DRY] write $target"
    echo "  [DRY] ensure ~/.local/bin in PATH (~/.bashrc, ~/.zshrc)"
    return 0
  fi

  mkdir -p "$target_dir"
  _personal_cmd_write_wrapper "$name" > "$target"
  chmod 755 "$target"
  ok_done "personal command installed: ~/.local/bin/$name"

  personal_cmd_ensure_path

  # If the current shell hasn't picked up ~/.local/bin yet, tell the
  # operator how to. PATH is set in rc files we just edited, but those
  # only take effect on next shell start (or after `source`).
  case ":$PATH:" in
    *":$HOME/.local/bin:"*) ;;
    *) warn "~/.local/bin not yet in PATH for this shell. Run:" \
            && echo "      source ~/.bashrc    # or open a new terminal" \
            && echo "      then: $name --help" ;;
  esac
}

# personal_cmd_uninstall <name>
#   Remove the wrapper file. Idempotent (no error if already gone).
#   Does NOT touch the PATH line in rc files — call personal_cmd_clean_path
#   from uninstall.sh once the last instance is gone.
personal_cmd_uninstall() {
  local name="${1:?personal_cmd_uninstall: name required}"
  local target="$HOME/.local/bin/$name"
  if [[ -e "$target" || -L "$target" ]]; then
    rm -f "$target"
  fi
}

# personal_cmd_ensure_path
#   Add ~/.local/bin to PATH in ~/.bashrc and ~/.zshrc, if and only if
#   the marker line isn't already there. Idempotent: running twice
#   doesn't duplicate the entry. Files that don't exist are left alone
#   (some shells use neither bashrc nor zshrc — those operators fix
#   their PATH manually).
personal_cmd_ensure_path() {
  local rc
  for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
    [[ -e "$rc" ]] || continue
    grep -Fq "$CLAUDIFY_PATH_MARKER" "$rc" && continue
    # Ensure file ends with a newline before appending so the marker
    # doesn't get mashed onto the last existing line.
    if [[ -s "$rc" ]] && [[ -n "$(tail -c1 "$rc")" ]]; then
      printf '\n' >> "$rc"
    fi
    printf '%s\n' "$CLAUDIFY_PATH_MARKER" >> "$rc"
    printf '%s\n' 'export PATH="$HOME/.local/bin:$PATH"' >> "$rc"
  done
}

# personal_cmd_clean_path
#   Remove the marker line and the export line below it from rc files.
#   Called by uninstall.sh after the last instance is removed, per
#   CLAUDE.md rule 10 (no orphaned env state on full uninstall). Lines
#   not added by Claudify are untouched.
personal_cmd_clean_path() {
  local rc tmp
  for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
    [[ -e "$rc" ]] || continue
    grep -Fq "$CLAUDIFY_PATH_MARKER" "$rc" || continue
    tmp="$(mktemp)"
    awk -v marker="$CLAUDIFY_PATH_MARKER" '
      $0 == marker          { skip = 1; next }
      skip == 1 && /^export PATH=.*\.local\/bin/ { skip = 0; next }
      skip == 1             { skip = 0 }
      { print }
    ' "$rc" > "$tmp"
    mv "$tmp" "$rc"
  done
}

# _personal_cmd_write_wrapper <name>
#   Emit the wrapper script to stdout. The OUTER heredoc (WRAPPER) is
#   unquoted so $name and ${CLAUDIFY_RAW_BASE} expand here at install
#   time; every other `$` is escaped so it's literal in the wrapper.
_personal_cmd_write_wrapper() {
  local name="$1"
  cat <<WRAPPER
#!/usr/bin/env bash
# Auto-generated by Claudify install for instance "$name".
# Edit at ~/.local/bin/$name only if you know what you're doing —
# this file gets regenerated on every Claudify install / update.

CLAUDIFY_INSTANCE="$name"

case "\${1:-}" in
  doctor)    exec bash <(curl -fsSL ${CLAUDIFY_RAW_BASE}/doctor.sh) --name "\$CLAUDIFY_INSTANCE" ;;
  update)    exec bash <(curl -fsSL ${CLAUDIFY_RAW_BASE}/update.sh) --name "\$CLAUDIFY_INSTANCE" ;;
  uninstall) exec bash <(curl -fsSL ${CLAUDIFY_RAW_BASE}/uninstall.sh) --name "\$CLAUDIFY_INSTANCE" "\${@:2}" ;;
  status)    systemctl --user status  "claudify-\$CLAUDIFY_INSTANCE" ;;
  logs)      journalctl --user -u     "claudify-\$CLAUDIFY_INSTANCE" -f ;;
  restart)   systemctl --user restart "claudify-\$CLAUDIFY_INSTANCE" ;;
  start)     systemctl --user start   "claudify-\$CLAUDIFY_INSTANCE" ;;
  stop)      systemctl --user stop    "claudify-\$CLAUDIFY_INSTANCE" ;;
  ""|help|-h|--help)
    cat <<HELP
\$CLAUDIFY_INSTANCE — your Claudify instance "\$CLAUDIFY_INSTANCE"

Usage:
  \$CLAUDIFY_INSTANCE doctor      Run health checks
  \$CLAUDIFY_INSTANCE update      Pull the latest Claudify and refresh in place
  \$CLAUDIFY_INSTANCE uninstall   Remove this instance entirely
  \$CLAUDIFY_INSTANCE status      Show systemd service status
  \$CLAUDIFY_INSTANCE logs        Follow service logs
  \$CLAUDIFY_INSTANCE restart     Restart the service
  \$CLAUDIFY_INSTANCE start       Start the service
  \$CLAUDIFY_INSTANCE stop        Stop the service
HELP
    ;;
  *)
    echo "Unknown subcommand: \$1" >&2
    "\$0" --help
    exit 2
    ;;
esac
WRAPPER
}
